# Generated by Django 5.1.4 on 2025-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spam',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
